###                                                                             ###
### Kör test varje gång vi öppnar en PR så man inte mergar nåt som är broken... ###
###                                                                             ###

name: Run Tests on PR/Merge

on:
  pull_request:
    branches: [main, develop] 
  push:
    branches: [main]  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -v
